name: Daily Trending

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run application
        run: go run .
        env:
          GITHUB_ACTIONS: "true"

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update daily trending"
          file_pattern: "daily_trending/*.html index.html"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>" 
